--- #YAML:1.0
name:               Alien-Libevent
version:            2.1
abstract:           Wrapper for installing libevent
author:
    - Thibault Duponchelle <thibault.duponchelle@gmail.com>
    - Johannes Plunien <plu@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    Archive::Tar:  0
    File::Spec:    0
    IO::Zlib:      0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
resources:
  IRC: irc://irc.perl.org/#native
  bugtracker: https://github.com/thibaultduponchelle/Alien-Libevent/issues
  homepage: https://metacpan.org/pod/Alien::Libevent
  repository: git://github.com/thibaultduponchelle/Alien-Libevent.git
